dirs:
  - /opt/personal
  - /u/workdir
ignore_extensions:
  - .iml
  - .ipr
  - .iws
  - .mbp
  - .apnx
  - .class
  - .jar
  - .lnk
  - .url
  - .bak
  - .tmp
  - .lpr
  - .o
  - .obj
  - .demo
  - .gem
  - .log
  - .sqlite3
  - .sqlite3-journal
  - .exe
  - .out
  - .dylib
ignore_directories:
  - tmp
  - temp
  - cache
  - logs
  - log
  - node_modules
osx_formats:
  - .app
  - .pages
  - .numbers
  - .key
  - .pvm
  - .graffle